#import = ["/Users/isaksamsten/.config/alacritty/light.toml"]
import = ["/Users/isaksamsten/.config/alacritty/dark.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "$HOME/.config/alacritty/tmux-attach.sh"]

[font]
size = 12.5

[font.glyph_offset]
x = 0
y = 0

[font.normal]
# family = "MesloLGM Nerd Font"
# family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
# family = "SFMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[46;5u"
key = "Period"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[44;5u"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[59;5u"
key = "Semicolon"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[mouse]
hide_when_typing = false

[window]
decorations = "transparent"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
option_as_alt = "OnlyLeft"

[window.padding]
x = 4
y = 4
